#!/bin/bash
echo "Adding files..."
git add . -A
echo "Commiting..."
git commit -m "Added"
echo "Pushing to GitHub..."
git push origin master | (yes 'kochetovdd' | head -n 1 && yes 'ms17081981ntv' | head -n 1)
echo "Pushing to Heroku..."
git push heroku master